### ISSUE TITLE
#define kOfxBitDepthHalf "OfxBitDepthHalf"

### ISSUE THREAD

**Issue by PierreJasmin** [ofxa/openfx#27]
/** @brief String used to label the OpenGL half float (16 bit floating point) sample format */
#define kOfxBitDepthHalf "OfxBitDepthHalf"

Should we make CPU branch support  kOfxBitDepthHalf in v1.4
If so this comment would need to be fixed

**Comment by PierreJasmin** [comment]
Also - if we make this available as CPU also - the header should mention v1.4 and over

**Comment by garyo** [comment]
this is done now, as of 1.4.
