### ISSUE TITLE
how do I grab individual image instead of a clip

### ISSUE THREAD

**Issue by miaoqiz** [ofxa/openfx#52]
Please ask questions ("how do I...?") on the [forum](https://groups.google.com/forum/#!forum/ofx-discussion), not by filing issues.

Read the contribution [guidelines](https://github.com/ofxa/openfx/wiki/Extending-OpenFX-Guidelines#submit-a-proposal-or-bug-report-to-review) first.

### Problem

Hi,

Thanks for the help in advance!

I am aware that there is "fetchClip()" method that grabs a clip. Is there a similar function that fetch each frame of the clip at a time so the frames can be processed sequentially inside a clip?

Thanks a lot and have a great day!

**Comment by miaoqiz** [comment]
Hi there,

I found the method of "fetchImage( t, bounds)", when I do the following:

----------------------------------------------------------------
OfxRectD * bounds_dst = new OfxRectD();
bounds_dst->x1 = 100;
bounds_dst->x2 = 1000;
bounds_dst->y1 = 100;
bounds_dst->y2 = 1000;

std::auto_ptr<OFX::Image> dst(m_DstClip->fetchImage(p_Args.time, bounds_dst));

----------------------------------------------------------------

The host app still shows the entire image instead of ROI.

Can you kindly advice?

Thanks a lot and have a great day!

**Comment by revisionfx** [comment]
Depends on what host?
In what app?

Pierre

**Comment by miaoqiz** [comment]
Hi,

Thanks for the help!

The host application is "Davinci Resolve" on Windows or Linux.

Also, just wondering is there a setting to suppress "slider" UI while still keeping the input field in "OFX::ImageEffectDescriptor"?

Thanks and have a good day!

**Comment by revisionfx** [comment]
There is a way to hide parameters if this is your question (secret property)
These questions are supported on the discussion list of the API
https://groups.google.com/forum/#!forum/ofx-discussion

It's preferrable you ask questions there
