### ISSUE TITLE
Overlay drawing API abstraction layer

### ISSUE THREAD

**Issue by fxtech** [ofxa/openfx#75]
# Open Effects Proposal for Standard Change

## Standard Change Workflow
- [x] Create proposal as issue (you're doing this now!)
- [x] Tag this issue with `standard change` tag
- [x] Identify subcommittee: at least one plug-in vendor, and at least one host
- [x] Discuss the idea in this issue
- [x] Write new or updated code and doc
- [x] Publish updates as a pull request (ideally on a `feature/PROPOSAL-NAME` branch)
   - [x] Make sure that PR references this issue number to keep them in sync
   - [x] Discuss and review code in the PR
   - [x] Meet all requirements below for accepting PR
- [x] When subcommittee signs off and other members don't have any further review comments, 
      maintainer merges PR to master which closes PR and issue

## Requirements for accepting a standard change:
- [x] Header files updated
- [x] Documentation updated
- [x] Release notes added
- [x] Compatibility review completed
- [x] Working code demonstrated with at least one host and one plugin
- [x] At least two members sign off
- [x] No further changes requested from membership

## Summary

A drawing utility suite to abstract away required use of OpenGL.

## Motivation

With OpenGL "going away" and new GPU and UI layers being used, we should provide an abstraction layer so plugins can draw on-screen controls or custom parameter UIs without requiring OpenGL.

## Problem

Demarcation, that's the problem!

## Impact

This suite is initially optional for both host and plugin use, and mostly embodied in a new header. If a host provides the suite, the plugin should make use of it, otherwise it is free to fall back to OpenGL. However, it should be considered as a required feature in future OFX versions, since OpenGL is slowly being deprecated.

One new POD type should be added to ofxCore.h.

## Documentation Impact

New documentation will have to be integrated.

## Stakeholders

Plugin writers will benefit as they will no longer be required to use OpenGL for their interacts.
Hosts will benefit as they will not be required to support OpenGL at all.

**Comment by barretpj** [comment]
Using this instead of letting plugins use GL directly would be a big win for Baselight - currently we have to intercept all interact GL calls to route them to our separate rendering process which is often on a separate system. It works but I'd be delighted not to have to do it!

**Comment by peterl-bmd** [comment]
Hosts will require some means to determine if a plugin is going to exclusively use the draw suite.  If we are not running in OpenGL, we cannot call interacts for a plugin that is going to make GL calls, without likely crashes/undefined behaviour.

It would also be nice to know if a plugin is usable at all without ihteracts.  In some cases, they are merely convenience, but it is still usable via the parameters directly; in others the interact might provide the only means of effectively using the plugin.

As such, perhaps a describe-time property (or multiple) for the above cases would be desirable?

**Comment by garyo** [comment]
Folks following this issue: please try out the new draw suite in `feature/drawSuite` branch -- the extension is now in review. Submit PRs as needed, and discuss here.

**Comment by barretpj** [comment]
```
	kOfxDrawTextAlignmentLeft = 0x0001,
	kOfxDrawTextAlignmentRight = 0x0002,
	kOfxDrawTextAlignmentTop = 0x0004,
	kOfxDrawTextAlignmentBottom = 0x008,
	kOfxDrawTextAlignmentBaseline = 0x010,
```

Bottom and Baseline are missing a 0 for consistent digit count.

**Comment by revisionfx** [comment]
Phil also mentions:  "Comment - if I was reviewing this code, I'd fail it because of the use of enum values which the client code is expected to | together to pass to an int parameter to drawText(). IMHO they should instead be const [unsigned] ints, or #defines. But not going to hold things up for this. "

**Comment by garyo** [comment]
Sample image, with RE:Vision plugin executing in Scratch:
![image](https://user-images.githubusercontent.com/139975/150607602-e95a259d-f927-4984-bc23-7b66da6b06ee.png)
Shows all new primitives working per the spec. Demonstrates the requirement of working with one plug-in and a host from a separate company.

**Comment by garyo** [comment]
This is complete and merged now with PR #90.

**Comment by MrKepzie** [comment]
> Hosts will require some means to determine if a plugin is going to exclusively use the draw suite. If we are not running in OpenGL, we cannot call interacts for a plugin that is going to make GL calls, without likely crashes/undefined behaviour.
> 
> It would also be nice to know if a plugin is usable at all without ihteracts. In some cases, they are merely convenience, but it is still usable via the parameters directly; in others the interact might provide the only means of effectively using the plugin.
> 
> As such, perhaps a describe-time property (or multiple) for the above cases would be desirable?

As this been explored further ? I have been wondering the same thing

**Comment by revisionfx** [comment]
There should probably be a V2 Interact suite that requires to use the DrawSuite.
Hosts that support OpenGL overlay draw can support both V1 and V2 without issues.
Hosts that can't support OpenGL overlay drawing would just support V2.
Plugins that don't know about V2, can still use OGL if V1 is supported.

- pierre

**Comment by fxtech** [comment]
I like that approach.

If anyone has already written to the older DrawSuite API released in 
Silhouette 2021.5, things won't break when the API is adjusted to the 
final revision for the 2022 release.

**Comment by revisionfx** [comment]
OK let's fast track that :)

I think if we just duplicate V1 suite and call it V2 and add as comment for V2 something like I said above, it's very soft as it's just a different pointer and the function pointers of the suite would be the same.  There needs to be a code change somehow as it did not work well before to just tie a spec change as doc with a release version...  

All I see with regards to Silhouette in our code is below, and otherwise turned off here until next release...  we should check suite from 2022.0 for SIlhouette for now?  We can follow-up offline... 
		if (mHost->isSilhouette())
		{ // workaround in Silhouette v <= 2020.5.5 cannot set during createInstance. XXX TO DO: check if it's fixed in next version

which is not particular to drawsuite, and not uncommon issue not to initially be able to initialize spatial coordinates as the clip is not defined yet...

**Comment by VegasSebastian** [comment]
From the host perspective, how to tell a plugin that overlays are supported (kOfxImageEffectPropSupportsOverlays) but only  using the draw suite? That would be the use case, If the host does not support OpenGL drawings. Even if  OfxInteractSuiteV1 is reported as not supported, most plugins will start drawing using OpenGL.

**Comment by garyo** [comment]
@VegasSebastian if your host supports the new DrawSuite, compliant plugins should use it. Of course older plugins won't, but they just won't work correctly in a non-OpenGL world, and that's something they would have to fix. So there's nothing more you can/should do than support the DrawSuite I think.
