### ISSUE TITLE
Custom plugin can't be detected by HitFilm pro 13

### ISSUE THREAD

**Issue by ysdffsdf124324** [ofxa/openfx#81]
Plugin I developed can't be  detected by hitFilm pro 13,  I sure the compiled .ofx file is in the proper place, and in the proper bundle format. Can anyone tell me how to solve this problem?

**Comment by garyo** [comment]
OS? Check that you're exporting the OFX symbols and they're not C++-mangled.

**Comment by ysdffsdf124324** [comment]
The operating system is windows10, and the exported plug-in extension is .ofx.  
What does "C++-mangled" mean?  ofx file was generated using Visual Studio 2017.

**Comment by garyo** [comment]
On Windows, you can use [Dependency Walker](https://www.dependencywalker.com/) to check what symbols are exported from a DLL (or .ofx). Make sure the OFX symbols use `__declspec(dllexport)` and `extern "C"`.
For more, see [MS extern "C"](https://docs.microsoft.com/en-us/cpp/build/exporting-cpp-functions-for-use-in-c-language-executables?view=vs-2019) and [MS __declspec](https://docs.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-declspec-dllexport?view=vs-2019.)

**Comment by Dithermaster** [comment]
Many hosts create a log file of bundles they have scanned, and what
plug-ins are found in them. Check with HitFilm to see if they do, or try
with a host that does.

///d@

**Comment by ysdffsdf124324** [comment]
I found the reason, because some dynamic libraries used in the plug-in are not linked.
